services:
  app:
    build:
      context: .
    container_name: go-app
    environment:
      NUTHATCH_KEY: ${NUTHATCH_KEY}
      DB_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}?sslmode=disable
      CACHE_HOST: ${CACHE_HOST}
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - go-app-network

  caddy:
    image: caddy
    container_name: go-app-caddy
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - caddy-config:/config
      - caddy-data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - go-app-network

  postgres:
    image: postgres:17-bookworm
    restart: always
    container_name: go-app-db
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [CMD-SHELL, "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - go-app-network

  migrations:
    image: ghcr.io/kukymbr/goose-docker:3.26.0
    restart: no
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: host=${POSTGRES_HOST} port=5432 user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB}
    volumes:
      - ./sql/schema:/migrations
    networks:
      - go-app-network

  caching:
    image: ghcr.io/willnorris/imageproxy
    restart: unless-stopped
    container_name: go-app-cache
    ports:
      - 1337:1337
    volumes:
      - cache-data:/tmp/imageproxy
    env_file:
      - ./.env
    command: -addr ${IMAGEPROXY_ADDR} -cache ${IMAGEPROXY_CACHE}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - go-app-network

volumes:
  pg-data:
  caddy-config:
  caddy-data:
  cache-data:

networks:
  go-app-network:
